title: La Farvica
email: farodriguezvivas (a) gmail . com
description: |+
  This website contains my opinions, writtings, tutorials or whatever I consider
  it worth to be written.
baseurl: ""
url: "http://farv.github.io/"
twitter_username: Pacobo
github_username:  Farv

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .c9
  - .git
  - .sass-cache

